#!/usr/bin/env bash
# Configuring Nginx to connect on post 80
rm /etc/nginx/sites-available/default
ln -a /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
